version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules # prevent the local node_modules folder to be overriden
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # make the chages to be synchronized immediately.
  api:
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
    